version: "3.8"

services:
  web:
    container_name: phoenix-web
    build:
      context: .
      dockerfile: packaging/docker/phoenix/Dockerfile
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - ./src/phoenix:/phoenix
    ports:
      - 8000:8000
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:14.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
    - 5432:5432


volumes:
  postgres_data:
